export const MODEL_REQUEST = 'requests'
export const MODEL_SIGNATURE = 'signatures'
export const MODEL_CONTENT = 'contents'
export const MODEL_MEMORY = 'memories'
export const MODEL_VIOLATION = 'violations'
export const MODEL_REQ_LOG = 'req_logs'
export const MODEL_APP_CONTEXT = 'app_contexts'
export const MODEL_APP_TSS_CONFIG = 'app_tss_configs'
