
export const APP_STATUS_NEW = "NEW"
export const APP_STATUS_TSS_GROUP_SELECTED = "TSS_GROUP_SELECTED"
export const APP_STATUS_DEPLOYED = "DEPLOYED"
export const APP_STATUS_PENDING = "PENDING"
export const APP_STATUS_EXPIRED = "EXPIRED"
